mtnptrsn_khaneliman_ssh_key: ENC[AES256_GCM,data:GVKNXiEADYO7oXGDshvjs+sBmkd5v3+5FU9UmkIXWNPdPa9cJ+C/V0KEKDPeQWwiAXiBzucq7SBRMgsmtDrLEFU4wIrWjZIibXxaLDOzANogK5ndbb6nepRPTdpFg4aK8JgXH+LP1dagO7JiU0uVrYqcWydCgBnRujXibnidXSf9UX7Lkwk+edaRBODY+h7468pSb7xoquilH6sXNwWzrTUBHltpMZnOm5KT71ZJpDW7VeTVKVUzrvjVVnOzhaKDibiT6n5HtuSRZncHJC+MA+wRur4NQqIRCguKHjpyCnIKpXeuJu4oWh+vXJwo7rlHsldsKNIxZAIlZCrz2Ixrgn5bdpRXApxzHAUF5ZnCYmWvL/sRT4RA3Tbs2H5R6hqi1n2owwEe4z5328PRU4U+Wm0+xeG5GBNrZusolStazYJ0UkgYkGikHidkzsNGHkiNTT3J6r+I6savr094U0gaOxd8cM3WRdHM+uF/TQakQKOeH2my6JBL6b0gI+N/15Jls+x4fXTK+58BUamz8Gxlet66uHhJx9OczEOlXAVmw+PMnG0=,iv:lE+OcAtXTns+pG1xyAQVEeyIAztXRJJnpCStJi356qE=,tag:6xKi/dza6+K83ztViPbmQw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTDI0WTQwV2N6UldjRHVB
        bDdDMFV0elVHeU9DSUpCSHlBVGxqL0oybWtjCjJiSWJGTFVQMDFpeEhDRHpKN2Vu
        NnE4RFpHc1p2bzI1NHpCenlpSDlGNjQKLS0tIGw3SEdpVld1eVQwU2J3SkFnV2hC
        VEc4dG5jNVBnMDJFbmdmci80OWJZRDAKhvEGparEWb5kNjQ4g8Tb1o7AY+xafTay
        IuM5GlynDSvYL0F3eKfbwwGKB1Ph/hO0nWnv8goAbI1pqjodHitKOA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0lUZTBIU0UvbDFGSXk5
        OHNBZlpzRkZtUk9HRWVVMWxidDUzaXFJd1UwCmNDM3JPL0NETkpFQmpSemZPYUpt
        RjZwK2o2VGNUT0NhSGFwank5NlltVEkKLS0tIHMxbmxqcm13NDI2NXFFVjFERXJt
        MFlOOFYwck5mams0R0VLM3hZQmF0SFkKLVDaIuigbcqWJTeVNtRujA/SXhhXkS7O
        jOV7w9JtE/Pe5qQNYmur7/ANrTri/LScCwlreLALm4MYRGwaDzXt/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-27T00:35:25Z"
  mac: ENC[AES256_GCM,data:1MB/TrUM53QKS2ZXH0mhbQI/qdM4Vgbw7BglqaWSb5pIIyRMMl3/gmqT6UZptx/uDve4F6v0OZf4BMDuz1LrPZ7VByfeKrfJy0+pbct9p9VzX7kxQiX+x23EDmtd3P8MezKas8KT3k0sMULVM2ZsGz/wUn3v94MUo2aIxiUeTpc=,iv:JoLfj4/tSPk5Vhdi96Tk61LluuTvBoOw3F/LjPLUf4Y=,tag:p/vuJo+PfM8y0COTIPz5mQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.0
